# Builds data/rt_example.rda: four participants, two conditions, 100 trials
# per cell, generated by r_contaminated() with the ground truth kept.
#
# Participants differ in two things the tutorial cares about. Their drift
# differs (the ability factor), and their contamination rate differs (2%, 5%,
# 10%, 15%), so that a per-participant estimate's error can be compared with
# that participant's own rate. The two conditions differ only in drift, by
# 0.4, as in the tutorial's Study 2.
#
# Run from the package root with the package loaded (devtools::load_all()).
# set.seed() is fine here: this is a data-preparation script, not package
# code.

set.seed(20260905)

participants <- data.frame(
  id = c("p1", "p2", "p3", "p4"),
  ability = c(0.85, 0.95, 1.05, 1.20),
  contam_rate = c(0.02, 0.05, 0.10, 0.15)
)
conditions <- data.frame(
  condition = c("hard", "easy"),
  drift_base = c(1.5, 1.9)
)
n_per_cell <- 100L

cells <- merge(participants, conditions)
cells <- cells[order(cells$id, cells$condition), ]

rt_example <- do.call(rbind, lapply(seq_len(nrow(cells)), function(i) {
  cell <- cells[i, ]
  true_drift <- cell$ability * cell$drift_base
  d <- r_contaminated(
    n_per_cell,
    generator = "ddm", process = "mixed", rate = cell$contam_rate,
    par = list(drift = true_drift, bound = 1.2, ndt = 0.30)
  )
  data.frame(
    id = cell$id,
    condition = cell$condition,
    trial = seq_len(n_per_cell),
    rt = d$rt,
    response = d$response,
    contaminant = d$contaminant,
    process = d$process,
    true_drift = true_drift,
    contam_rate = cell$contam_rate,
    stringsAsFactors = FALSE
  )
}))
rt_example$condition <- factor(rt_example$condition, levels = c("hard", "easy"))
row.names(rt_example) <- NULL

usethis::use_data(rt_example, overwrite = TRUE)
