#' Simulated response times from four participants, with ground truth
#'
#' @description
#' A small data set for the examples and the vignette: four participants, two
#' conditions, 100 trials per cell, generated by [r_contaminated()] from a
#' diffusion core with contaminants from all three processes. Because the data
#' are simulated, every trial carries the truth a real data set cannot: whether
#' it was a contaminant, and which process produced it.
#'
#' @format A `data.frame` with 800 rows and 9 columns:
#'
#'   \describe{
#'     \item{`id`}{participant, `"p1"` to `"p4"`.}
#'     \item{`condition`}{factor, `"hard"` or `"easy"`; the base drifts the
#'       two conditions are built from differ by 0.4, before the participant's
#'       ability factor multiplies both (see Details).}
#'     \item{`trial`}{trial number within the cell, 1 to 100.}
#'     \item{`rt`}{response time in seconds.}
#'     \item{`response`}{`1` for a correct response, `0` for an error.}
#'     \item{`contaminant`}{logical ground truth.}
#'     \item{`process`}{`"clean"`, `"leading_edge"`, `"delay"`, or
#'       `"informationless"`.}
#'     \item{`true_drift`}{the drift the cell was generated from.}
#'     \item{`contam_rate`}{the participant's contamination rate: `.02`, `.05`,
#'       `.10`, and `.15` for `p1` to `p4`.}
#'   }
#'
#' @details
#' The participants differ in two things at once. Their drift differs, by a
#' fixed ability factor of `0.85`, `0.95`, `1.05`, and `1.20` on a base drift
#' of `1.5` (hard) and `1.9` (easy), with `bound = 1.2` and `ndt = 0.30`
#' throughout. And their contamination rate differs, so that the error in a
#' participant's estimate can be set against their own rate. That comparison is
#' the question the package's companion tutorial asks of every preprocessing
#' pipeline.
#'
#' The generating script is `data-raw/rt_example.R` in the source repository;
#' the seed is fixed there, not in the package.
#'
#' @seealso [r_contaminated()] to generate data shaped like your own task.
#'
#' @examples
#' head(rt_example)
#' table(rt_example$id, rt_example$process)
#'
#' @keywords datasets
"rt_example"
